GET http://localhost:3000/categories

###
GET http://localhost:3000/posts

###
# Post with valid ID
GET http://localhost:3000/posts/1

###
# Post with invalid ID
GET http://localhost:3000/posts/99

###
# Login with correct details:
# username: 'bobo', email: 'bobo@test.com', password: '123456'
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "auth":
  {
    "email": "nyomi@test.com",
    "password": "123456"
  }
}

###
# Login with incorrect details:
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "auth":
  {
    "email": "bobo@test.com",
    "password": "12345"
  }
}

###
# Register with correct details
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "nyomi1@test.com",
  "username": "nyomi1",
  "password": "123456",
  "password_confirmation": "123456"
}

###
# With Token
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2MzczMDQ0NjJ9.JT2lZN3iiel91bFtIjBl7GLqVEv4hr4QmNdKgcfEs1Y"

{
  "title": "I've got a token!",
  "content": "Woohooo!",
  "category_id": 1
}

###
# Edit post 1
PUT http://localhost:3000/posts/1
Content-Type: application/json

{
  "title": "I am authenticated",
  "content": "Edited"
}

###
# Delete post 1
DELETE http://localhost:3000/posts/1